// R40a: a child graph's `inherits` is generated by the editor, never authored. Membership is
// what propagates (spec §8.4), so every write that changes who reads a provider has to
// reconsider what the members' expansions inherit.
//
// When several hosts in the same parent expand the same child file, the child inherits the
// union of what any of those hosts can read — matching workspace lint's multi-host rule.

import {
  formatListValue,
  getProp,
  resolvedExpandPath,
  setPreambleField,
  type FlowDocument,
  type FlowNode,
} from '../../shared/flow-format.js';
import * as FlowDoc from '../flow-doc.js';
import type { DocumentOwner } from '../canvas/expansion.js';
import type { ActionContinuation, CommitTiming } from '../edit-session.js';

export interface InheritsSyncDeps {
  suspendAction(): ActionContinuation;
  expandTargetDoc(path: string): FlowDocument | null;
  ensureDocument(path: string): Promise<FlowDocument | null>;
  applyToDoc(owner: DocumentOwner, mutation: () => void, options?: { commit?: CommitTiming }): void;
}

export function syncInheritsForMembers(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  memberNames: Iterable<string>,
): void {
  for (const memberName of new Set(memberNames)) void syncInheritsForMember(deps, owner, memberName);
}

export async function syncInheritsForMember(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  memberName: string,
): Promise<void> {
  const node = FlowDoc.nodesIn(owner.doc.items).find((candidate) => candidate.name === memberName);
  if (!node) return;
  // A local `graph:` block has no preamble to carry `inherits`; its nodes read through this host.
  const path = resolvedExpandPath(getProp(node, 'expand'), owner.path);
  if (!path) return;

  // Fetching the child resumes in a later turn when it was not already loaded, so the write
  // belongs to the action that changed the membership rather than to a step of its own.
  const continuation = deps.suspendAction();
  const doc = deps.expandTargetDoc(path) ?? await deps.ensureDocument(path);
  if (!doc) return;

  continuation.resume(() => {
    const readable = readableContextsForChildPath(owner, path);
    if (sameNameSet(FlowDoc.inheritedContextNames(doc), readable)) return;
    deps.applyToDoc(
      { doc, path },
      () => setPreambleField(doc, 'inherits', readable.length > 0 ? formatListValue(readable) : null),
      { commit: 'now' },
    );
  });
}

/** Union of contexts readable by every host in `owner` that expands to `childPath`. */
export function readableContextsForChildPath(owner: DocumentOwner, childPath: string): string[] {
  const hosts = hostsExpandingTo(owner, childPath);
  const names = new Set<string>();
  for (const host of hosts) {
    for (const name of FlowDoc.contextNamesReadableBy(owner.doc, host.name)) names.add(name);
  }
  return [...names];
}

function hostsExpandingTo(owner: DocumentOwner, childPath: string): FlowNode[] {
  return FlowDoc.nodesIn(owner.doc.items).filter((node) => {
    return resolvedExpandPath(getProp(node, 'expand'), owner.path) === childPath;
  });
}

export function sameNameSet(current: string[], next: string[]): boolean {
  return current.length === next.length && current.every((name) => next.includes(name));
}
