// R40a: a child graph's `inherits` is generated by the editor, never authored. Membership is
// what propagates (spec §8.4), so every write that changes who reads a provider has to
// reconsider what the members' expansions inherit.
//
// When several hosts in the same parent expand the same child file, the child inherits the
// union of what any of those hosts can read — matching workspace lint's multi-host rule.

import {
  formatListValue,
  getProp,
  resolvedExpandPath,
  setPreambleField,
  type FlowDocument,
  type FlowNode,
} from '../../shared/flow-format.js';
import * as FlowDoc from '../flow-doc.js';
import type { DocumentOwner } from '../canvas/expansion.js';
import type { ActionContinuation, CommitTiming } from '../edit-session.js';

export interface InheritsSyncDeps {
  suspendAction(): ActionContinuation;
  expandTargetDoc(path: string): FlowDocument | null;
  ensureDocument(path: string): Promise<FlowDocument | null>;
  applyToDoc(owner: DocumentOwner, mutation: () => void, options?: { commit?: CommitTiming }): void;
}

export function syncInheritsForMembers(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  memberNames: Iterable<string>,
): void {
  for (const memberName of new Set(memberNames)) void syncInheritsForMember(deps, owner, memberName);
}

export async function syncInheritsForMember(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  memberName: string,
): Promise<void> {
  const node = FlowDoc.nodesIn(owner.doc.items).find((candidate) => candidate.name === memberName);
  if (!node) return;
  // A local `graph:` block has no preamble to carry `inherits`; its nodes read through this host.
  const path = resolvedExpandPath(getProp(node, 'expand'), owner.path);
  if (!path) return;
  await syncInheritsForPath(deps, owner, path, new Set());
}

// Rewrites the `inherits` of the file at `path` from the hosts in `owner`, strips the
// `updates:` claims that rewrite makes unreadable, then descends into that file's own
// expansions so a provider lost here is lost through the whole chain. `visited` records
// every file already used as an owner or rewritten, so an expand cycle cannot write a
// descendant's readable set back onto an ancestor (R6). A path reached by several parents
// is synced from the first one that reaches it.
export async function syncInheritsForPath(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  path: string,
  visited: Set<string>,
): Promise<void> {
  visited.add(owner.path);
  if (visited.has(path)) return;
  visited.add(path);
  const loaded = deps.expandTargetDoc(path);
  if (loaded == null) {
    // Fetching the child resumes in a later turn when it was not already loaded, so the write
    // belongs to the action that changed the membership rather than to a step of its own.
    const continuation = deps.suspendAction();
    const fetched = await deps.ensureDocument(path);
    if (!fetched) return;
    continuation.resume(() => rewriteInheritsAndDescend(deps, owner, { doc: fetched, path }, visited));
    return;
  }
  rewriteInheritsAndDescend(deps, owner, { doc: loaded, path }, visited);
}

function rewriteInheritsAndDescend(
  deps: InheritsSyncDeps,
  owner: DocumentOwner,
  child: DocumentOwner,
  visited: Set<string>,
): void {
  const readable = readableContextsForChildPath(owner, child.path);
  deps.applyToDoc(
    child,
    () => {
      if (!sameNameSet(FlowDoc.inheritedContextNames(child.doc), readable)) {
        setPreambleField(child.doc, 'inherits', readable.length > 0 ? formatListValue(readable) : null);
      }
      // `updates:` is kept in step with what the file can now back: anything the rewrite made
      // unreadable is stripped, so a provider that left the chain takes its claims with it (R40c).
      FlowDoc.removeUnreadableUpdates(child.doc);
    },
    { commit: 'now' },
  );
  for (const host of FlowDoc.allNodes(child.doc)) {
    const grandchildPath = resolvedExpandPath(getProp(host, 'expand'), child.path);
    if (grandchildPath) void syncInheritsForPath(deps, child, grandchildPath, visited);
  }
}

/** Union of contexts readable by every host in `owner` that expands to `childPath`. */
export function readableContextsForChildPath(owner: DocumentOwner, childPath: string): string[] {
  const hosts = hostsExpandingTo(owner, childPath);
  const names = new Set<string>();
  for (const host of hosts) {
    for (const name of FlowDoc.contextNamesReadableBy(owner.doc, host.name)) names.add(name);
  }
  return [...names];
}

function hostsExpandingTo(owner: DocumentOwner, childPath: string): FlowNode[] {
  return FlowDoc.allNodes(owner.doc).filter((node) => {
    return resolvedExpandPath(getProp(node, 'expand'), owner.path) === childPath;
  });
}

export function sameNameSet(current: string[], next: string[]): boolean {
  return current.length === next.length && current.every((name) => next.includes(name));
}
